#!/usr/bin/env bash
# Configure my domain zone:
# www --> 87235-lb-01 54.198.54.85
# web-01 --> 87235-web-01 54.86.220.207
# web-02 --> 87235-web-02 54.237.23.192

# -- To be evaluated --
# domain_information () {
#     line=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
#     echo "$2 $line" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
# }

# if [ "$#" == 1 ]
