#!/usr/bin/env bash
# Find out what's keeping your ubuntu container's Nginx installation from listening to port 80.
# Nginx must run and listen to port 80.

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
