#!/usr/bin/env bash
# Displays "To infinity and beyone" indefinitely with
# a sleep 2 inbetween each iteration.
#  Displays "I am invincible!!!" inbetween each iteration

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "I am Invincible!!!"' SIGTERM
done
